# Generated by Django 2.2 on 2021-02-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_auto_20210213_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachernot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=150)),
                ('attach_file', models.FileField(upload_to='notice/')),
            ],
        ),
    ]
