# Generated by Django 2.2 on 2021-02-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_teachernot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events_mod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_name', models.CharField(max_length=50)),
                ('events_link', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Events',
            },
        ),
    ]
