# Generated by Django 2.2 on 2021-02-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_headline_mod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headline_mod',
            old_name='headlines_link',
            new_name='headline_link',
        ),
        migrations.RenameField(
            model_name='headline_mod',
            old_name='headlines_name',
            new_name='headline_name',
        ),
        migrations.AlterModelTable(
            name='headline_mod',
            table='Headline',
        ),
    ]
