# Generated by Django 2.2 on 2021-02-14 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0006_auto_20210214_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headline_mod',
            old_name='headline_link',
            new_name='line_link',
        ),
        migrations.RenameField(
            model_name='headline_mod',
            old_name='headline_name',
            new_name='line_name',
        ),
    ]
