# Generated by Django 2.2 on 2021-02-14 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0007_auto_20210215_0001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Headline_mod',
        ),
    ]
