# Generated by Django 2.2 on 2021-02-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0008_delete_headline_mod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line_mod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_n', models.CharField(max_length=40)),
                ('line_l', models.CharField(max_length=40)),
            ],
        ),
    ]
