# Generated by Django 2.2 on 2021-02-15 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0009_line_mod'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Line_mod',
            new_name='Line',
        ),
    ]
