# Generated by Django 2.2 on 2021-02-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0010_auto_20210215_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='title_g',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teachernot',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
