# Generated by Django 2.2 on 2021-02-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0011_auto_20210215_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('deg', models.CharField(max_length=150)),
                ('img', models.FileField(upload_to='images/')),
                ('join_date', models.FileField(max_length=20, upload_to='')),
            ],
        ),
    ]
