# Generated by Django 2.2 on 2021-02-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0012_teacher_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_data',
            name='join_date',
            field=models.CharField(max_length=20),
        ),
    ]
