# Generated by Django 2.2 on 2021-02-15 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0013_auto_20210215_1212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Line',
        ),
    ]
